# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: typesplit_central_dongle dongle_display
    artifact-name: typesplit_central_dongle
  - board: nice_nano_v2
    shield: typesplit_central_left
    artifact-name: typesplit_central_left
  - board: nice_nano_v2
    shield: typesplit_peripheral_left
    artifact-name: typesplit_peripheral_left
  - board: nice_nano_v2
    shield: typesplit_peripheral_right
    artifact-name: typesplit_peripheral_right
  - board: nice_nano_v2
    shield: settings_reset